// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Rbl.Models
{
    public partial class RBLContext : DbContext
    {
        public RBLContext()
        {
        }

        public RBLContext(DbContextOptions<RBLContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<ScoresAll> ScoresAll { get; set; }
        public virtual DbSet<ScoresByIndustry> ScoresByIndustry { get; set; }
        public virtual DbSet<ScoresByTicker> ScoresByTicker { get; set; }
        public virtual DbSet<ScoresTopTen> ScoresTopTen { get; set; }
        public virtual DbSet<ScoresTotal> ScoresTotal { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<ScoresAll>(entity =>
            {
                entity.ToView("ScoresAll_2021");
            });

            modelBuilder.Entity<ScoresByIndustry>(entity =>
            {
                entity.ToView("ScoresByIndustry_2021");
            });

            modelBuilder.Entity<ScoresByTicker>(entity =>
            {
                entity.ToView("ScoresByTicker_2021");
            });

            modelBuilder.Entity<ScoresTopTen>(entity =>
            {
                entity.ToView("ScoresTopTen_2021");
            });

            modelBuilder.Entity<ScoresTotal>(entity =>
            {
                entity.ToView("ScoresTotal_2021");
                entity.Property(x => x.TotalScore).HasColumnName("total_score");
                entity.Property(x => x.Ticker).HasColumnName("ticker");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}