// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace Rbl.Models
{
    [Keyless]
    public partial class ScoresTotal
    {
        public string Ticker { get; set; }
        public double? TotalScore { get; set; }
    }
}